title: "NightB1ade’s Recipes"
titles_from_headings:
    enabled: false
defaults:
    -
        scope:
            path: Mains
        values:
            layout: recipe
    -
        scope:
            path: Utility
        values:
            layout: recipe
